// coursesData.js
// Static mock data — replace with API calls when backend is ready
// Future endpoints: GET /api/languages | GET /api/concepts

export const languagesData = [
  {
    id: 1,
    title: "C Programming",
    description: "Master the fundamentals of C including pointers, memory management, and system-level programming.",
    progress: 72,
    topics: 18,
    level: "Beginner",
    icon: "C",
    color: "#1a73e8",
  },
  {
    id: 2,
    title: "C++",
    description: "Object-oriented programming, STL, templates, and competitive programming patterns.",
    progress: 55,
    topics: 24,
    level: "Intermediate",
    icon: "C++",
    color: "#0d47a1",
  },
  {
    id: 3,
    title: "Java",
    description: "Core Java, OOP, collections, multithreading, and Spring Boot basics.",
    progress: 40,
    topics: 30,
    level: "Intermediate",
    icon: "Jv",
    color: "#e65100",
  },
  {
    id: 4,
    title: "Python",
    description: "Python syntax, data structures, libraries, scripting, and algorithm implementation.",
    progress: 88,
    topics: 22,
    level: "Beginner",
    icon: "Py",
    color: "#1565c0",
  },
  {
    id: 5,
    title: "JavaScript",
    description: "ES6+, async/await, closures, DOM manipulation, and interview-focused JS patterns.",
    progress: 63,
    topics: 26,
    level: "Intermediate",
    icon: "JS",
    color: "#f57f17",
  },
  {
    id: 6,
    title: "Go (Golang)",
    description: "Concurrency, goroutines, channels, and building efficient backend services.",
    progress: 20,
    topics: 15,
    level: "Advanced",
    icon: "Go",
    color: "#006064",
  },
];

export const conceptsData = [
  {
    id: 1,
    title: "Operating Systems",
    description: "Process scheduling, memory management, deadlocks, synchronization, and file systems.",
    progress: 48,
    topics: 20,
    icon: "OS",
    color: "#6a1b9a",
  },
  {
    id: 2,
    title: "Database Management",
    description: "DBMS concepts, normalization, transactions, indexing, and query optimization.",
    progress: 65,
    topics: 18,
    icon: "DB",
    color: "#00695c",
  },
  {
    id: 3,
    title: "Computer Networks",
    description: "OSI model, TCP/IP, routing, DNS, HTTP/HTTPS, and network security basics.",
    progress: 35,
    topics: 16,
    icon: "CN",
    color: "#1565c0",
  },
  {
    id: 4,
    title: "System Design",
    description: "Scalability, load balancing, caching, microservices, and designing distributed systems.",
    progress: 25,
    topics: 14,
    icon: "SD",
    color: "#c62828",
  },
  {
    id: 5,
    title: "Object Oriented Design",
    description: "SOLID principles, design patterns (Creational, Structural, Behavioral), and UML.",
    progress: 58,
    topics: 12,
    icon: "OO",
    color: "#e65100",
  },
  {
    id: 6,
    title: "Computer Architecture",
    description: "CPU internals, memory hierarchy, instruction sets, pipelining, and cache design.",
    progress: 30,
    topics: 10,
    icon: "CA",
    color: "#37474f",
  },
];
